# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Database Backup

on:
  workflow_dispatch:
    inputs:
      unique_id:
      description: 'run identifier'
      required: false
jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.unique_id}}
        run: echo run identifier ${{ inputs.unique_id }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pause for 10 seconds
        run: |
          sleep 10
